### ISSUE TITLE
apple splash screens cuts off SVG

### ISSUE THREAD

**Issue by tripflex** [vite-pwa/assets-generator#16]
Testing out the new handling for apple splash screens (thanks for that!!) I was having an issue though with the generated files (off an SVG) being cut off.

The only way I was able to resolve this was to set:

```
resizeOptions: { fit: 'contain' },
```

Not sure if maybe this should be a default value?  I can open a PR to add to documentation if you would like (if don't want to add this as a "default" option

**Comment by userquin** [comment]
Yeah, it should be the default
