### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by simkuns** [vite-pwa/assets-generator#2]
`yarn generate-pwa-assets --preset minimal public/icon.png`

yarn run v1.22.19
$ pwa-assets-generator
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Changing node_modules/@vite-pwa/assets-generator/bin/pwa-assets-generator.mjs EOL sequence from CRLF to LF fixed issue

**Comment by userquin** [comment]
@simkuns thx, should be fixed in `0.0.3` version
