### ISSUE TITLE
Favicon not being generated if its size doesn't match any of the transparent asset sizes

### ISSUE THREAD

**Issue by lgaspari** [vite-pwa/assets-generator#5]
Hey there!

First of all, thanks for such amazing library 🚀. I've been using the PWA Assets Generator to ease the assets generation for my Progressive Web Application and it certainly delivers!

---

Now, moving to the issue, I noticed that when using a custom favicon size that isn't listed as part of the transparent asset sizes, it won't generate the `.ico` file:

```ts
export default defineConfig({
  images: ['public/logo.svg'],
  preset: {
    apple: {
      sizes: [180],
    },
    maskable: {
      sizes: [512],
    },
    transparent: {
      favicons: [[48, 'favicon.ico']], // custom size
      sizes: [64, 192, 512], // 48 size not listed here
    },
  },
});
```

Then, this is the output (notice the `Generated ICO file` isn't in the log):

![image](https://github.com/vite-pwa/assets-generator/assets/20128985/bc8bb806-4e95-45db-9065-8787b0d89140)

However, if we change the configuration to the following:

```ts
transparent: {
  favicons: [[48, 'favicon.ico']],
  sizes: [48, 64, 192, 512], // include 48 size in the list
},
```

Then, the output includes the `.ico` file:

![image](https://github.com/vite-pwa/assets-generator/assets/20128985/60edfbcc-e0d1-4782-9259-17b0c042cd45)

---

Not really sure if this is a feature or a bug, but I found it by looking at the source code [build.ts#L53](https://github.com/vite-pwa/assets-generator/blob/main/src/build.ts#L53) where it checks if the favicon size is part of the transparent assets sizes array, otherwise it just skips it.

As a workaround, I'm generating an extra asset (`pwa-48x48.png`) that I'm deleting manually afterwards because otherwise the favicon won't be generated. If there's a better approach, I haven't found it yet!

Thanks in advance to everyone :)

**Comment by userquin** [comment]
Maybe we can generate the transparent png and the ico and then remove the png...

PR welcome

**Comment by userquin** [comment]
@lgaspari something like this? In my case adding 48 favicon to pwa assets in the test folder.

![imagen](https://github.com/vite-pwa/assets-generator/assets/6311119/c8786658-8fad-420b-b7e8-fd9b50e94223)

**Comment by lgaspari** [comment]
Indeed @userquin, now it works like a charm ✨ 

Appreciate that you took the time not only to look into this issue but also fixing it in almost no time 😄

![image](https://github.com/vite-pwa/assets-generator/assets/20128985/2476aa97-de3c-4aff-955d-a612a0a8b306)
